import type { Metadata } from "next";
// imported font

import { Inter } from "next/font/google";
import "./globals.css";
import NavbarDemo  from "../components/Navbar";
// const defaultUrl = process.env.VERCEL_URL ? https://${process.env.VERCEL_URL}
// : "http://localhost:3000";

const defaultUrl = "http://localhost:3000";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark" >
      <body className={inter.className}>
        <div className="relative w-full flex items-center
        justify-center">
          {/* <NavbarDemo/> */}
        </div>
        {children}
      </body>
    </html>
  );
}
